/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    id("org.jetbrains.kotlin.jvm") version "1.8.10"
}

repositories {
   mavenCentral()
}

dependencies {
   implementation(kotlin("stdlib"))
}

tasks.withType<KotlinCompile> {
   kotlinOptions {
      jvmTarget = "17"
   }
}


